import type { DeviceAcquisition } from './manipulationProjection';
import type { ActorFootPlant } from '../../domain/actorMotion';
import type { GalleryActorEvent } from '../../domain/gallery/actor';
import type { VaultActorEvent } from '../../domain/vault/actor';
import type { createGalleryAudio } from '../../audio';
import type { CameraMatrices, ChapterRuntime, InteractableDefinition } from '../../domain/firstPerson/types';
import type { TutorialMilestones, TutorialTracker } from '../../domain/firstPerson/tutorial';
import type { interactionCue } from '../../domain/firstPerson/interactionCue';
import type { FirstPersonInput } from './touchInput';
import type { FirstPersonDiagnostics } from './diagnostics';
import type { NotebookMaskPreview } from './notebookCamera';
import type { TheatreCue } from '../../domain/theatre/cues';
import type { StageTargetPresentation } from '../../domain/stageKit/presentation';

/** Controller state contracts have no runtime imports or initialization. */
export type RuntimeController = {
  runtime: ChapterRuntime;
  notebookPreview?: NotebookMaskPreview | undefined;
  viewport?: { width: number; height: number };
  horrorIntensity: 'standard' | 'subdued';
  audio?: ReturnType<typeof createGalleryAudio>;
  audioSequence: number;
  pendingFootstepDistance: number;
  pendingActorFootstepDistance: number;
  pendingStageSounds: { x: number; y: number; z: number }[];
  pendingActorPlants: ActorFootPlant[];
  pendingActorEvents: (GalleryActorEvent | VaultActorEvent)[];
  pendingExitImpact: boolean;
  pendingProjectorPulse: boolean;
  pendingTheatreCues: TheatreCue[];
  actorNotice?: { sequence: number; text: string };
  equipmentInvestigationSequence?: number | undefined;
  retired: boolean;
  screenReader: boolean;
  commandSequence: number;
  lastReceivedSequence: number;
  feedbackMessage: string;
  presentationFeedbackSequence: number;
  pendingPresentationFeedback: { session: number; sequence: number; callback: () => void }[];
  lastCommand?: { type: string; accepted: boolean; reason: string };
  lastCompareMs: number;
  input: FirstPersonInput;
  lab: boolean;
  sensitivity: number;
  verticalSensitivity: number;
  tutorial: TutorialTracker;
  simpleStep: number;
  viewCommandRevision: number;
  matrices: CameraMatrices | undefined;
  diagnostics: FirstPersonDiagnostics;
  metrics: { frames: number; elapsed: number; drawCalls: number; geometries: number; textures: number };
};
export type RuntimeSnapshot = { stageTarget?: StageTargetPresentation; feedbackScope: string; acquisition?: DeviceAcquisition; actorNotice?: { sequence: number; text: string }; equipmentInvestigationSequence?: number; runtime: ChapterRuntime; tutorial: TutorialMilestones; target: InteractableDefinition | undefined; cue: ReturnType<typeof interactionCue>; objective: string; direction: string; key: string };
