/* Metro requires literal asset requires to bundle local audio in an offline build. */
import type { AudioSourceId } from './types';

export const AUDIO_SOURCES: Readonly<Record<AudioSourceId, number>> = Object.freeze({
  footstep: require('../../assets/audio/footstep.wav'),
  interaction: require('../../assets/audio/interaction.wav'),
  mechanism: require('../../assets/audio/mechanism.wav'),
  ambience: require('../../assets/audio/ambience.wav'),
  cloth: require('../../assets/audio/cloth.wav'),
  'door-impact': require('../../assets/audio/door-impact.wav'),
  shepard: require('../../assets/audio/shepard.wav'),
  title_theme: require('../../assets/audio/music/title_theme.m4a'),
  exploration: require('../../assets/audio/music/exploration.m4a'),
  suspicion: require('../../assets/audio/music/suspicion.m4a'),
  pursuit: require('../../assets/audio/music/pursuit.m4a'),
  release: require('../../assets/audio/music/release.m4a'),
  chapter_end: require('../../assets/audio/music/chapter_end.m4a'),
  'grip': require('../../assets/audio/physical/grip.wav'),
  'key': require('../../assets/audio/physical/key.wav'),
  'ratchet': require('../../assets/audio/physical/ratchet.wav'),
  'bell': require('../../assets/audio/physical/bell.wav'),
  'isolation': require('../../assets/audio/physical/isolation.wav'),
  'power': require('../../assets/audio/physical/power.wav'),
  'step-a': require('../../assets/audio/physical/step-a.wav'),
  'step-b': require('../../assets/audio/physical/step-b.wav'),
  'cloth-metal': require('../../assets/audio/physical/cloth-metal.wav'),
  'outdoor': require('../../assets/audio/physical/outdoor.wav'),
  'room-gallery': require('../../assets/audio/physical/room-gallery.wav'),
  'room-vault': require('../../assets/audio/physical/room-vault.wav'),
  'room-theatre': require('../../assets/audio/physical/room-theatre.wav'),
  'room-mirror': require('../../assets/audio/physical/room-mirror.wav'),
  'room-control': require('../../assets/audio/physical/room-control.wav'),
});
